-- 212 Café — seed data
--
-- Generated by data/generate-seed.mjs from data/menu.json, crawled 2026-08-26 from
-- 212.smaresto.com/selforder/api/products. Item names, Arabic names, descriptions and
-- prices are the café's REAL data — none of it is invented.
--
-- Two deliberate departures from the source, both documented in data/FINDINGS.md:
--   1. "Extra Milk -", "Extra Milk" and "Extras" are excluded as products. They are
--      add-ons that only exist as separate line items because the incumbent POS has no
--      modifier support. They are re-created below as modifier options at their real
--      prices (QAR 3 and QAR 10).
--   2. Modifier prices marked "UNCONFIRMED" have no counterpart in the source data.
--      They are proposals and MUST be confirmed with the owner before the demo is
--      presented as a quote.
--
-- Re-runnable: upserts key on source_id.

begin;

-- --------------------------------------------------------------- settings

insert into business_settings (id, latitude, longitude)
values (1, 25.368100, 51.527700)
on conflict (id) do nothing;

-- Hours per their Instagram (12:00–00:00 daily). Google shows ~12:30–23:00, so these
-- need confirming — which is exactly why they are editable rows, not frontend constants.
insert into business_hours (day_of_week, opens_at, closes_at, is_closed) values
  (0, '12:00', '00:00', false),
  (1, '12:00', '00:00', false),
  (2, '12:00', '00:00', false),
  (3, '12:00', '00:00', false),
  (4, '12:00', '00:00', false),
  (5, '12:00', '00:00', false),
  (6, '12:00', '00:00', false)
on conflict (day_of_week) do nothing;

-- ------------------------------------------------------------- categories

insert into menu_categories (source_id, name_en, name_ar, slug, sort_order) values
  (1, 'Hot Beverage', 'مشروبات ساخنة', 'hot-beverage', 0),
  (2, 'Cold Beverage', 'مشروبات باردة', 'cold-beverage', 10),
  (3, 'Sweets-Pastry', 'حلويات ومعجنات', 'sweets-pastry', 20),
  (4, 'Savoury', 'مأكولات', 'savoury', 30),
  (5, 'Salads', 'سلطات', 'salads', 40),
  (6, 'Brunch', 'فطور متأخر', 'brunch', 50)
on conflict (source_id) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar, sort_order = excluded.sort_order;

-- ------------------------------------------------------------------ items
-- 53 sellable items across 6 categories.

insert into menu_items
  (source_id, category_id, sku, name_en, name_ar, description_en, description_ar,
   price, image_path, is_available, is_signature, sort_order)
values
  (2, (select id from menu_categories where source_id = 1), '0002', 'Americano', 'امريكانو', 'Classic Americano Double shot of rich espresso diluted with hot water, creating a smooth, light-bodied cup with a full-flavored coffee aroma.', 'أمريكانو كلاسيك شوت مزدوج من الإسبريسو الغني المخفف بالماء الساخن، ليمنحك كوباً متوازناً وخفيف القوام مع عبق القهوة الغني.', 26.00, '/menu/0002-americano.webp', true, false, 10),
  (3, (select id from menu_categories where source_id = 1), '0003', 'Tiramisu Latte', 'تيراميسو لاتيه', '', '', 29.00, '/menu/0003-tiramisu-latte.webp', true, false, 20),
  (4, (select id from menu_categories where source_id = 1), '0004', 'Cappucino', 'كابوتشينو', 'Classic Cappuccino A rich shot of double espresso topped with equal parts steamed milk and a thick, silky layer of milk foam, dusted with cocoa powder.', 'كابوتشينو كلاسيك شوت غني من الإسبريسو المزدوج يعلوه مزيج متوازن من الحليب المبخر ورغوة الحليب المخملية الكثيفة، مع لمسة خفيفة من بودرة الكاكاو', 27.00, '/menu/0004-cappucino.webp', true, false, 30),
  (5, (select id from menu_categories where source_id = 1), '0005', 'Chamomile Tea', 'شاي البابونج', 'Chamomile Tea (Hot / Iced) A soothing, caffeine-free infusion of premium whole chamomile flowers, offering a delicate floral aroma and subtle notes of honey.', 'شاي البابونج (حار / بارد) مزمور مهدئ وخالٍ من الكافيين من أزهار البابونج الكاملة الفاخرة، يتميز بنكهة زهرية لطيفة ولمسات خفيفة من العسل.', 25.00, '/menu/0005-chamomile-tea.webp', true, false, 40),
  (11, (select id from menu_categories where source_id = 1), '0011', 'Green Tea', 'شاي اخضر', '', '', 25.00, '/menu/0011-green-tea.webp', true, false, 50),
  (17, (select id from menu_categories where source_id = 1), '0017', 'Spanish Latte', 'سبانيش لاتيه', '', '', 29.00, '/menu/0017-spanish-latte.webp', true, false, 60),
  (18, (select id from menu_categories where source_id = 1), '0018', 'Latte', 'لاتيه', 'Latte Smooth, rich espresso combined with silky, steamed micro-foam milk for a perfectly balanced and velvety coffee experience.', 'لاتيه إسباديسو غني وناعم ممزوج بالحليب المبخر ذو الرغوة المخملية الحريرية، لتجربة قهوة متوازنة وفاخرة.', 28.00, '/menu/0018-latte.webp', true, false, 70),
  (19, (select id from menu_categories where source_id = 1), '0019', 'V60', 'في ٦٠', '', '', 36.00, '/menu/0019-v60.webp', true, false, 80),
  (95, (select id from menu_categories where source_id = 1), '0095', 'Ceremonial Matcha Latte', 'ماتشا لاتيه الاحتفالية', 'Ceremonial Matcha Latte (Hot / Iced) Japanese ceremonial matcha whisked to perfection and combined with smooth, velvety milk for a vibrant, earthy taste with natural sweetness. Served with a shot of espresso.', 'سيريمونيال ماتشا لاتيه (حار / بارد) ماتشا يابانية سيريمونيال مخفوقة بإتقان وممزوجة بالحليب المخملي الناعم، لمذاق غني ومنعش وحلاوة طبيعية. يُقدّم مع شوت إسبريسو.', 30.00, '/menu/0095-ceremonial-matcha-latte.webp', true, false, 90),
  (107, (select id from menu_categories where source_id = 1), '0107', 'Double Espresso', 'دابل اسبريسو', 'Double Espresso A bold, concentrated double shot of specialty coffee, extracted to highlight rich flavors, natural sweetness, and a velvety crema layer.', 'دبل إسبريسو جرعة مضاعفة غنية ومكثفة من القهوة المختصة، تم استخلاصها بعناية لإبراز النكهات الغنية، الحلاوة الطبيعية، وطبقة الكريما المخملية.', 22.00, '/menu/0107-double-espresso.webp', true, false, 100),
  (108, (select id from menu_categories where source_id = 1), '0108', 'English Breakfast Tea', 'شاي احمر', 'English Breakfast Tea A classic, full-bodied black tea brew delivering a rich, robust malt flavor with a bright golden-amber hue and a refreshing finish.', 'شاي أحمر إنجليش بريكفاست الشاي الأحمر الكلاسيكي الفاخر بعبير قوي ونكهة غنية ومكثفة، يتميز بلونه الذهبي الدافئ ولمسته المنعشة.', 25.00, '/menu/0108-english-breakfast-tea.webp', true, false, 110),
  (109, (select id from menu_categories where source_id = 1), '0109', 'Single Espresso', 'اسبريسو', '', '', 18.00, '/menu/0109-single-espresso.webp', true, false, 120),
  (110, (select id from menu_categories where source_id = 1), '0110', 'Flat White', 'فلات وايت', 'Flat White A double shot of rich espresso topped with velvety, micro-foamed steamed milk for a smooth, coffee-forward taste and silky mouthfeel.', 'فلات وايت جرعة مضاعفة من الإسبريسو الغني تعلوها رغوة حليب ناعمة ومخملية لمذاق متوازن يبرز نكهة القهوة الغنية وقوام حريري.', 27.00, '/menu/0110-flat-white.webp', true, false, 130),
  (115, (select id from menu_categories where source_id = 1), '0115', 'Non-coffee Matcha', 'الماتشا مع الحليب', 'Matcha Latte Japanese matcha whisked to perfection and paired with silky, steamed micro-foam milk for a smooth, earthy, and antioxidant-rich beverage.', 'ماتشا لاتيه ما تشا يابانية فاخرة بدرجة احتفالية مقتناة بعناية، مخفوقة بإتقان وممزوجة مع الحليب المبخر ذو الرغوة المخملية لمشروب ناعم، غني ومضاد للأكسدة.', 28.00, '/menu/0115-non-coffee-matcha.webp', true, false, 140),
  (216, (select id from menu_categories where source_id = 1), '0216', 'Cortado', 'كورتادو', 'Cortado A precise 1:1 balance of rich espresso cut with equal parts warm, silky steamed milk, served in a classic glass.', 'كورتادو توازن دقيق بنسبة 1:1 من الإسبريسو الغني مع كمية مساوية من الحليب المبخر الدافئ والمخملي، يُقدّم في كوب زجاجي كلاسيكي.', 27.00, '/menu/0216-cortado.webp', true, false, 150),
  (16, (select id from menu_categories where source_id = 2), '0016', '212-Signature', '212 سيقنيجر', 'A rich shot of espresso blended with fresh milk, crushed Oreo, and our signature homemade chocolate sauce.', 'جرعة غنية من الإسبريسو ممتزجة بالحليب الطازج، وقطع الأوريو المقرمشة، مع صوص الشوكولاتة الخاص المحضّر منزلياً', 36.00, '/menu/0016-212-signature.webp', true, true, 160),
  (34, (select id from menu_categories where source_id = 2), '0034', 'the 3 Layers', '3 لايرز', '', '', 36.00, '/menu/0034-the-3-layers.webp', true, true, 170),
  (39, (select id from menu_categories where source_id = 2), '0039', 'Normal water', 'ماء', '', '', 10.00, '/menu/0039-normal-water.webp', true, false, 180),
  (40, (select id from menu_categories where source_id = 2), '0040', 'Sparkling water', 'ماء غازي', '', '', 13.00, '/menu/0040-sparkling-water.webp', true, false, 190),
  (101, (select id from menu_categories where source_id = 2), '0101', 'Affogato', 'افوكاتو', 'Classic Affogato A scoop of rich, creamy vanilla gelato "drowned" in a freshly pulled shot of hot, double espresso. The perfect balance of hot and cold, sweet and bold.', 'أفوغاتو كلاسيك كرة من جيلاتو الفانيليا الغنية يسكب عليها "شوت" دافئ من الإسبريسو المزدوج الطازج. التوازن المثالي بين الحرارة والبرودة، والحلاوة والمرارة.', 26.00, '/menu/0101-affogato.webp', true, false, 200),
  (120, (select id from menu_categories where source_id = 2), '0120', 'Unique Strawberry Matcha', 'ماتشا الفراولة', '', '', 36.00, '/menu/0120-unique-strawberry-matcha.webp', true, false, 210),
  (132, (select id from menu_categories where source_id = 2), '0132', 'Fresh Orange Juice', 'برتقال', 'Fresh Orange Juice 100% freshly squeezed ripe oranges, naturally sweet, vibrant, and packed with refreshing citrus taste.', 'عصير برتقال طازج عصير برتقال طازج 100٪ من حبات البرتقال الناضجة، بحلاوة طبيعية ونكهة حمضية منعشة.', 32.00, '/menu/0132-fresh-orange-juice.webp', true, false, 220),
  (135, (select id from menu_categories where source_id = 2), '0135', 'Limited Colada', 'كولادا', 'Limited Colada A signature seasonal beverage layered with sweet pineapple juice and rich, thick mango juice, topped with silky coconut cream and finished with a crispy coconut crunch.', 'ليميتد كولادا مشروب موسمي مميز بطبقات من عصير الأناناس الحلو وعصير المانجو الكثيف، تعلوه كريمة جوز الهند الحريرية ومُزيّن بقرمشة جوز الهند الطازجة.', 29.00, '/menu/0135-limited-colada.webp', true, false, 230),
  (208, (select id from menu_categories where source_id = 2), '0208', 'Hiby Splash', 'هيبي سبلاش', 'Hiby Splash A vibrant cold-pressed iced hibiscus tea infused with peach and mixed berry flavor, bright citrus, and fresh mint.', 'هايب سبلاش شاي كركديه بارد ومعصور على البارد غني بنكهات الخوخ والتوت المشكل، الحمضيات المنعشة، والنعناع الطازج.', 29.00, '/menu/0208-hiby-splash.webp', true, false, 240),
  (209, (select id from menu_categories where source_id = 2), '0209', 'Mango Red Horizon', 'المانجو الأحمر', '', '', 32.00, '/menu/0209-mango-red-horizon.webp', true, false, 250),
  (210, (select id from menu_categories where source_id = 2), '0210', 'Passion Wave', 'باشن ويف', '', '', 33.00, '/menu/0210-passion-wave.webp', true, false, 260),
  (211, (select id from menu_categories where source_id = 2), '0211', 'Sunrise', 'سان رايز', '', '', 30.00, '/menu/0211-sunrise.webp', true, false, 270),
  (49, (select id from menu_categories where source_id = 3), '0049', 'Brownies Chocolate Bomb', 'شوكولاتة براونيز', 'Fresh Homemade Brownie Fresh homemade brownie topped with a bowl of creamy vanilla ice cream and warm specialty chocolate sauce to pour over and melt the top.', 'براوني طازج محضر لدينا براوني طازج ومحضر لدينا يعلوه وعاء من آيس كريم الفانيليا الكريمي مع صوص الشوكولاتة الخاص الدافئ للسكب فوقه وتذويب', 45.00, '/menu/0049-brownies-chocolate-bomb.webp', true, true, 280),
  (52, (select id from menu_categories where source_id = 3), '0052', 'The French Toast', 'فرانش توست', 'The French Toast Two pieces of golden, thick-cut artisan brioche soaked in a rich vanilla-cinnamon custard, seared to perfection. Served with salted caramel drizzle, fresh berries, and a side of vanilla ice cream.', 'الفرنش توست شريحتان سميكتان من خبز البريوش الذهبي الفاخر، مغمورتان في مزيج الكاسترد بالفانيليا والقرفة الغني ومحمصلتان بإتقان. تُقدّم مع لمسة من الكراميل المملح، الفواكه التوتية الطازجة، وجانب من أيس كريم الفانيليا.', 50.00, '/menu/0052-the-french-toast.webp', true, true, 290),
  (143, (select id from menu_categories where source_id = 3), '0143', 'ice tissu cake', 'فيكتوريا كيك', 'Iced Tissue Cake An exquisite creation crafted in the shape of roasted coffee beans, featuring ultra-thin, tissue-soft layered cake infused with chilled cream and rich cocoa.', 'آيس تيشو كيك ابتكار فني ساحر على شكل حبوب القهوة المحمصة، يتميز بطبقات كيك ناعمة ورقيقة كالأنسجة، محشوة بالكريمة الباردة والكاكاو الغني.', 39.00, '/menu/0143-ice-tissu-cake.webp', true, false, 300),
  (203, (select id from menu_categories where source_id = 3), '0203', 'CHEESE CAKE', 'تشيز كيك', '', '', 38.00, '/menu/0203-cheese-cake.webp', true, false, 310),
  (204, (select id from menu_categories where source_id = 3), '0204', 'PECAN MELT', 'ذوبان البقان', 'Pecan Melt An exquisite dessert sculpted in the shape of a pecan nut, filled with signature homemade cream, a dual-biscuit base, and rich melted caramel, topped with a crunchy pecan nut finish.', 'بيكان ميلت حلوى مبتكرة ومصممة على شكل حبة البيكان، محشوة بالكريمة الخاصة المنزلية، طبقتين من البسكويت الهش، والكراميل الذائب، تعلوها مقرمشات البيكان المحمصة.', 42.00, '/menu/0204-pecan-melt.webp', true, false, 320),
  (205, (select id from menu_categories where source_id = 3), '0205', 'Golden Hive Cake', 'كيكة خلية النحل الذهبية', 'Golden Hive Cake Delicate, golden layers of honey-infused cake separated by light, velvety cream, finished with a subtle honey-crumb topping.', 'كيكة خلية النحل الذهبية طبقات ذهبية رقيقة وهشة من الكيك المحضر بعسل النحل الطبيعي، تفصل بينها كريمة مخملية خفيفة، ومتوجة بفتات العسل الهش.', 38.00, '/menu/0205-golden-hive-cake.webp', true, false, 330),
  (206, (select id from menu_categories where source_id = 3), '0206', 'Double D', 'دابل دي', 'Double D Rich chocolate sponge layered with creamy espresso-infused filling, nestled between two distinct house-made biscuits, topped with melted rich chocolate and a crunchy chocolate crumble.', 'دبل دي كيكة إسفنجية بالشوكلاتة الغنية مع طبقات من الكريمة بنكهة الإسبريسو، بين نوعين من البسكويت المحضر لدينا، يغلوها الشوكولاتة الغنية المذابة مع كرانشي الشوكولاتة المقرمش.', 37.00, '/menu/0206-double-d.webp', true, false, 340),
  (56, (select id from menu_categories where source_id = 4), '0056', 'Turkey Sandwich', 'ساندويش التركي', '', '', 38.00, '/menu/0056-turkey-sandwich.webp', true, false, 350),
  (58, (select id from menu_categories where source_id = 4), '0058', 'Cheese Croissant', 'كرواسون جبن', '', '', 26.00, '/menu/0058-cheese-croissant.webp', false, false, 360),
  (59, (select id from menu_categories where source_id = 4), '0059', 'Chocolate Croissant', 'كرواسون الشوكولاتة', '', '', 26.00, '/menu/0059-chocolate-croissant.webp', false, false, 370),
  (76, (select id from menu_categories where source_id = 4), '0076', 'Penne Pasta', 'باستا بيني', 'Penne Pasta Al dente penne folded into an Italian special sauce—a rich combination of three distinct sauces creating a creamy white base with tender pieces of chicken breast. Topped with aged Parmesan, white cheddar, and a pinch of fresh chives and parsley. Served with two slices of toasted bread to enjoy every drop of sauce.', 'بيني باستا باستا البيني المطبوخة ببراعة وممزوجة بصلصة إيطالية خاصة,مزيج غني من ثلاثة أنواع مختلفة من الصلصات لابتكار قاعدة بيضاء كريمية مع قطع طرية من صدر الدجاج. تعلوها جُبنة البارميزان المعتقة، الشيدر الأبيض، ورشة البقدونس الطازج. تُقدّم مع شريحتين من الخبز المحمص للاستمتاع بآخر قطرة من الصلصة.', 42.00, '/menu/0076-penne-pasta.webp', true, false, 380),
  (155, (select id from menu_categories where source_id = 4), '0155', 'Halloumi Sandwich', 'ساندويش الحلوم', 'Halloumi Sandwich Pan-seared golden halloumi layered in warm artisan brioche with signature za''atar, fresh homemade green pesto, smooth avocado guacamole, wild rocket, and sliced tomato, finished with extra virgin olive oil and sweet pomegranate molasses.', 'ساندويتش حلوم شرائح جبن الحلوم الذهبية المحمرة في خبز البريوش الحرفي الدافئ مع الزعتر الفاخر، بيستو الأعشاب الخضراء المحضر منزلياً، واكامولي الأفوكادو الناعم، جرجير بري، وشرائح الطماطم، تعلوها لمسة من زيت الزيتون البكر ودبس الرمان الحلو.', 35.00, '/menu/0155-halloumi-sandwich.webp', true, false, 390),
  (157, (select id from menu_categories where source_id = 4), '0157', 'Cheesy Roasted Beef Sandwich', 'ساندويش اللحم', 'Cheesy Roasted Beef Sandwich Tender roasted beef strips layered with rich homemade red pesto, melted mozzarella cheese, fresh tomato slices, and crisp greens, served warm in a toasted artisan bun.', 'ساندويش شرائح اللحم البقري بالجبن شرائح لحم بقر مشوي طرية مع صوص البيستو الأحمر المحضّر لدينا، جبن الموزاريلا المذاب، شرائح الطماطم الطازجة، والخضار الخضراء المنعشة، تُقدّم دافئة في خبز محمص فاخر.', 39.00, '/menu/0157-cheesy-roasted-beef-sandwich.webp', true, false, 400),
  (160, (select id from menu_categories where source_id = 4), '0160', 'Plain Croissant', 'كرواسون', '', '', 19.00, '/menu/0160-plain-croissant.webp', false, false, 410),
  (202, (select id from menu_categories where source_id = 4), '0202', 'Barbecue Chicken Sandwich', 'دجاج بصلصة الباربيكيو  سندويش', 'BBQ Chicken Sandwich Tender, shredded grilled chicken tossed in a rich, smoky barbecue sauce, topped with melted cheese, fresh pomegranate seeds, and toasted pumpkin seeds, served inside a toasted brioche bun.', 'ساندويتش دجاج باربكيو شرائح دجاج مشوية وطرية ممزوجة بصوص الباربكيو المدخن والغني، يعلوها الجبن المذاب، حبات الرمان الطازجة، وبذور القرع المحمصة، تقدم داخل خبز البريوش المحمص.', 36.00, '/menu/0202-barbecue-chicken-sandwich.webp', true, false, 420),
  (207, (select id from menu_categories where source_id = 4), '0207', 'Tuna AVocado', 'تونة ا فوكاتو', '', '', 38.00, '/menu/0207-tuna-avocado.webp', true, false, 430),
  (214, (select id from menu_categories where source_id = 4), '0214', 'Creamy Egg with Chicken', 'بيض كريمي مع دجاج', 'Creamy Egg with Chicken Velvety soft-scrambled eggs paired with tender herb-marinated chicken, served over toasted artisan brioche and garnished with fresh chives.', 'بيض كريمي مع الدجاج بيض مخفوق ناعم ومخملي يُقدّم مع دجاج طري متبل بالأعشاب، فوق شريحة من خبز البريوش المحمص ومزين بالثوم المعمر الطازج.', 32.00, '/menu/0214-creamy-egg-with-chicken.webp', true, false, 440),
  (163, (select id from menu_categories where source_id = 5), '0163', 'Chicken Ceaser Salad', 'سلطة السيزر مع الدجاج', 'Chicken Caesar Salad Tender grilled chicken breast served over crisp romaine lettuce, tossed in rich Caesar dressing, topped with shaved Parmesan cheese and garlic butter croutons.', 'سلطة سيزر الدجاج شرائح صدور الدجاج المشوية الطرية على طبقة من خس الرومين الطازج، ممزوجة بصلصة السيزر الغنية، يعلوها جبن البارميزان المبشور ومكعبات الخبز المحمص بالثوم والزبدة.', 38.00, '/menu/0163-chicken-ceaser-salad.webp', true, false, 450),
  (201, (select id from menu_categories where source_id = 5), '0201', 'Rocca with Quinoa', 'الجرجير مع الكينوا', 'Rocca with Quinoa Salad Crisp rocket leaves and fluffy organic quinoa tossed with cherry tomatoes, fresh pomegranate seeds, toasted nuts, and crunchy baked corn pieces, served with tender grilled chicken breast . Finished with a signature blend of balsamic vinaigrette and zesty Italian dressing.', 'سلطة الروكا مع الكينوا أوراق الجرجير الطازجة مع الكينوا العضوية الهشة، مطعّمة بطماطم شيري، حبات الرمان الطازجة، المكسرات المحمصة، وقطع الذرة ، تُقدّم مع صدر الدجاج المشوي الطري. ممزوجة بلمسة خاصة من صلصة البلسميك والتتبيلة الإيطالية المنعشة.', 34.00, '/menu/0201-rocca-with-quinoa.webp', true, false, 460),
  (66, (select id from menu_categories where source_id = 6), '0066', 'Eggs Benedict', 'بيض البينيدكت', 'Eggs Benedict Crisp layered potato pavé topped with creamy mashed avocado, two perfectly poached eggs, and rich hollandaise sauce, finished with a pinch of sweet paprika, fresh rocca, and crumbled feta.', 'إيجز بينيديكت طبقات البطاطس المقرمشة يعلوها مهروس الأفوكادو الكريمي، بيضتان مسلوقتان بدقة، وصوص الهولنديز الغني، مع لمسة من البابريكا الحلوة، الجرجير الطازج، ورشة من جبن الفيتا.', 52.00, '/menu/0066-eggs-benedict.webp', true, true, 470),
  (67, (select id from menu_categories where source_id = 6), '0067', '3 Mini Sandwiches', 'ساندويتشات صغير 3', 'Falafel Donuts Crisp, donut-shaped artisanal falafel crafted from spiced chickpeas and fresh herbs, served over smooth tahini drizzle, garnished with pickled turnips, wild rocket, toasted sesame, and pomegranate seeds.', 'دونات الفلافل فلافل حرفية مقرمشة على شكل دونات محضرة من الحمص المتبل والأعشاب الطازجة، تُقدّم فوق صوص الطحينة الناعمة، وتُزيَّن باللفت المخلل، الجرجير البري، السمسم المحمص، وحبات الرمان.', 32.00, '/menu/0067-3-mini-sandwiches.webp', true, false, 480),
  (70, (select id from menu_categories where source_id = 6), '0070', 'Healthy Granola', 'جرانولا', 'Healthy Granola Bowl House-baked toasted oat granola blended with mixed nuts and seeds, served over silky Greek yogurt, topped with fresh seasonal berries, chia seeds, and a drizzle of pure honey.', 'جرانولا صحية جرانولا الشوفان المخبوزة منزلیاً والمحمصة مع مكسرات وبذور مشكلة، تُقدّم فوق زبادي يوناني حريري، وتُزيَّن بالتوت الفاكهي الطازج، بذور الشيا، ورذاذ من العسل الصافي.', 40.00, '/menu/0070-healthy-granola.webp', true, false, 490),
  (75, (select id from menu_categories where source_id = 6), '0075', 'Green Shakshooka', 'شكشوكة', '', '', 36.00, '/menu/0075-green-shakshooka.webp', false, false, 500),
  (175, (select id from menu_categories where source_id = 6), '0175', 'Shakshooka', 'شكشوكة', 'Shakshooka Two eggs gently cooked and nestled in a rich, slow-simmered sauce of vine-ripened tomatoes, a sweet bell pepper mixture, garlic, and aromatic Mediterranean spices. Served warm with artisan Arabic bread.', 'شكشوكة بيضتان مطهوتان ببراعة ورفق داخل صلصة غنية ومطهوة ببطء من الطماطم الناضجة، مزيج الفلفل الرومي الحلو، الثوم، والتوابل المتوسطية العطرية. تُقدّم دافئة مع الخبز العربي المخبوز على الطريقة الحرفية.', 36.00, '/menu/0175-shakshooka.webp', true, false, 510),
  (212, (select id from menu_categories where source_id = 6), '0212', 'Greek Omlette', 'اومليت يوناني', 'Greek Omelette Fluffy eggs folded with tangy Greek feta cheese, sweet cherry tomatoes, Kalamata olives, and fresh greens, finished with aromatic oregano and delicate herbs.', 'أومليت يوناني بيض هشش مطوي مع جبن الفيتا اليوناني الفاخر، الطماطم الكرزية الحلوة، زيتون الكالاماتا، والأوراق الخضراء الطازجة، يُكَمَّل بنكهة الزعتر البري والأعشاب العطرية.', 32.00, '/menu/0212-greek-omlette.webp', true, false, 520),
  (213, (select id from menu_categories where source_id = 6), '0213', 'French Omlette', 'ااومليت فرنسي', 'French Omelette Smooth, golden, and soft-folded eggs with a rich, velvety center, finished with a brush of fine butter and freshly chopped herbs.', 'أومليت فرنسي بيض مطوي بعناية بقوام ذهبي أملس ومركز كريمي طري، مطلي بلمسة من الزبدة الفاخرة ومزين بالأعشاب الطازجة.', 27.00, '/menu/0213-french-omlette.webp', true, false, 530)
on conflict (source_id) do update set
  category_id    = excluded.category_id,
  name_en        = excluded.name_en,
  name_ar        = excluded.name_ar,
  description_en = excluded.description_en,
  description_ar = excluded.description_ar,
  price          = excluded.price,
  image_path     = excluded.image_path,
  is_available   = excluded.is_available,
  is_signature   = excluded.is_signature,
  sort_order     = excluded.sort_order;

-- -------------------------------------------------------------- modifiers
--
-- The incumbent has none of this. Prices sourced from their own add-on products where
-- one exists; everything marked UNCONFIRMED is a proposal awaiting the owner's sign-off.

insert into menu_item_modifier_groups (id, name_en, name_ar, min_select, max_select, sort_order) values
  ('11111111-1111-4111-8111-000000000001', 'Milk',       'الحليب',      1, 1, 10),
  ('11111111-1111-4111-8111-000000000002', 'Size',       'الحجم',       1, 1, 20),
  ('11111111-1111-4111-8111-000000000003', 'Extras',     'إضافات',      0, 4, 30),
  ('11111111-1111-4111-8111-000000000004', 'Add to dish','إضافة للطبق', 0, 3, 40)
on conflict (id) do nothing;

insert into menu_item_modifier_options (group_id, name_en, name_ar, price_delta, is_default, sort_order) values
  -- Milk: the QAR 3 delta is their real "Extra Milk" price.
  ('11111111-1111-4111-8111-000000000001', 'Whole milk',   'حليب كامل الدسم', 0,               true,  10),
  ('11111111-1111-4111-8111-000000000001', 'Skimmed milk', 'حليب خالي الدسم', 0,               false, 20),
  ('11111111-1111-4111-8111-000000000001', 'Oat milk',     'حليب الشوفان',    3.00, false, 30),
  ('11111111-1111-4111-8111-000000000001', 'Almond milk',  'حليب اللوز',      3.00, false, 40),
  -- Size: UNCONFIRMED — no size data exists in the source menu.
  ('11111111-1111-4111-8111-000000000002', 'Regular', 'عادي', 0,    true,  10),
  ('11111111-1111-4111-8111-000000000002', 'Large',   'كبير', 6.00, false, 20),
  -- Drink extras: extra shot / syrup are UNCONFIRMED proposals.
  ('11111111-1111-4111-8111-000000000003', 'Extra espresso shot', 'شوت إسبريسو إضافي', 6.00, false, 10),
  ('11111111-1111-4111-8111-000000000003', 'Vanilla syrup',       'صوص الفانيليا',     3.00, false, 20),
  ('11111111-1111-4111-8111-000000000003', 'Caramel syrup',       'صوص الكراميل',      3.00, false, 30),
  ('11111111-1111-4111-8111-000000000003', 'Decaf',               'خالي الكافيين',     0,    false, 40),
  -- Food add-on priced from their real "Extras" product (QAR 10).
  ('11111111-1111-4111-8111-000000000004', 'Extra portion', 'حصة إضافية', 10.00, false, 10),
  ('11111111-1111-4111-8111-000000000004', 'Add avocado',   'إضافة أفوكادو', 10.00, false, 20)
on conflict do nothing;

-- Attach Milk/Size/Extras to milk-based and brewed drinks only; espresso-only and
-- non-coffee items are deliberately excluded.
insert into menu_item_modifier_links (item_id, group_id, sort_order)
select mi.id, g.id, g.sort_order
from menu_items mi
cross join menu_item_modifier_groups g
join menu_categories mc on mc.id = mi.category_id
where g.id in (
        '11111111-1111-4111-8111-000000000001',
        '11111111-1111-4111-8111-000000000002',
        '11111111-1111-4111-8111-000000000003')
  and mc.name_en in ('Hot Beverage', 'Cold Beverage')
  and mi.name_en not in ('Normal water', 'Sparkling water', 'Fresh Orange Juice')
on conflict do nothing;

insert into menu_item_modifier_links (item_id, group_id, sort_order)
select mi.id, '11111111-1111-4111-8111-000000000004', 40
from menu_items mi
join menu_categories mc on mc.id = mi.category_id
where mc.name_en in ('Brunch', 'Salads', 'Savoury')
on conflict do nothing;

-- ----------------------------------------------------------------- tables
-- 12 tables. The incumbent's QR carried ?table_id=12, so 12 keeps the demo familiar.

insert into cafe_tables (label, seats, sort_order)
select lpad(n::text, 2, '0'), case when n % 4 = 0 then 4 else 2 end, n * 10
from generate_series(1, 12) as n
on conflict (label) do nothing;

-- One active opaque token per table. 128 bits of entropy, revocable — the fix for ?table_id=12.
insert into table_qr_tokens (table_id)
select t.id from cafe_tables t
where not exists (
  select 1 from table_qr_tokens q where q.table_id = t.id and q.is_active
);

commit;
