-- 212 Café — editable copy, seeded from the compiled dictionary
--
-- GENERATED by data/generate-content-seed.mjs from src/lib/copy.json. Do not hand-edit:
-- regenerate it instead, or the database and the app's fallback will disagree about what
-- the default copy is.
--
-- `on conflict do nothing` on purpose. This runs on every fresh clone, and must never
-- overwrite copy the owner has already changed through /admin/content.

begin;

insert into site_content (key, value_en, value_ar, kind, group_name, sort_order) values
  ('heroLocation', 'Marina Twin Tower A · 30th Floor · Lusail', 'برج مارينا التوأم أ · الطابق الثلاثون · لوسيل', 'text', 'hero', 1009),
  ('heroLine1', 'Coffee', 'قهوة', 'text', 'hero', 1010),
  ('heroLine2', 'above the city', 'فوق المدينة', 'text', 'hero', 1011),
  ('heroSub', 'Specialty coffee, desserts and brunch, thirty floors over Lusail Marina.', 'قهوة مختصة وحلويات وفطور متأخر، على ارتفاع ثلاثين طابقاً فوق مارينا لوسيل.', 'text', 'hero', 1012),
  ('viewEyebrow', 'The View', 'الإطلالة', 'text', 'view', 2017),
  ('viewTitle', 'Lusail’s best view, and we mean it.', 'أجمل إطلالة في لوسيل، ونعني ذلك.', 'text', 'view', 2018),
  ('viewBody1', 'From the 30th floor of Marina Twin Tower A, the Katara Towers curve out of the marina and the Gulf runs to the horizon. Every table is a window seat.', 'من الطابق الثلاثين في برج مارينا التوأم أ، تنحني أبراج كتارا خارجة من المارينا ويمتد الخليج حتى الأفق. كل طاولة هنا بإطلالة.', 'text', 'view', 2019),
  ('viewBody2', 'It is the reason people come once, and the reason they come back.', 'هو السبب في أن يزورنا الناس أول مرة، والسبب في عودتهم.', 'text', 'view', 2020),
  ('viewFullMenu', 'View full menu', 'عرض القائمة كاملة', 'text', 'view', 2026),
  ('signaturesEyebrow', 'Signatures', 'الأطباق المميزة', 'text', 'signatures', 3021),
  ('signaturesTitle', 'What we are known for', 'ما نشتهر به', 'text', 'signatures', 3022),
  ('signatureTag', 'Signature', 'مميز', 'text', 'signatures', 3023),
  ('menuEyebrow', 'The Menu', 'القائمة', 'text', 'menu', 4024),
  ('menuTitle', 'things worth the lift', 'صنفاً تستحق الصعود', 'text', 'menu', 4025),
  ('menuPageTitle', 'Everything we serve', 'كل ما نقدمه', 'text', 'menu', 4029),
  ('menuPageSub', 'sections. Prices in Qatari riyal.', 'أقسام. الأسعار بالريال القطري.', 'text', 'menu', 4030),
  ('closedNow', 'Closed', 'مغلق', 'text', 'visit', 5016),
  ('visitEyebrow', 'Visit', 'زورونا', 'text', 'visit', 5032),
  ('visitTitle', 'Thirty floors up', 'ثلاثون طابقاً للأعلى', 'text', 'visit', 5033),
  ('getDirections', 'Get directions', 'الاتجاهات', 'text', 'visit', 5034),
  ('hours', 'Hours', 'ساعات العمل', 'text', 'visit', 5035),
  ('closed', 'Closed', 'مغلق', 'text', 'visit', 5036),
  ('hoursNote', 'Hours are managed by the café and update here automatically.', 'يدير المقهى ساعات العمل وتُحدَّث هنا تلقائياً.', 'text', 'visit', 5037),
  ('footerBlurb', 'Specialty coffee, desserts and brunch, 30 floors above Lusail Marina.', 'قهوة مختصة وحلويات وفطور متأخر، ثلاثون طابقاً فوق مارينا لوسيل.', 'text', 'footer', 6038),
  ('footerAddress', 'Marina Twin Tower A, 30th Floor, Lusail, Qatar', 'برج مارينا التوأم أ، الطابق الثلاثون، لوسيل، قطر', 'text', 'footer', 6039),
  ('brandTagline', 'Lusail’s Best View', 'أجمل إطلالة في لوسيل', 'text', 'navigation', 7000),
  ('navView', 'The View', 'الإطلالة', 'text', 'navigation', 7001),
  ('navSignatures', 'Signatures', 'الأطباق المميزة', 'text', 'navigation', 7002),
  ('navMenu', 'Menu', 'القائمة', 'text', 'navigation', 7003),
  ('navVisit', 'Visit', 'زورونا', 'text', 'navigation', 7004),
  ('fullMenu', 'Full Menu', 'القائمة الكاملة', 'text', 'navigation', 7005),
  ('openMenu', 'Open menu', 'فتح القائمة', 'text', 'navigation', 7006),
  ('closeMenu', 'Close menu', 'إغلاق القائمة', 'text', 'navigation', 7007),
  ('back', 'Back', 'رجوع', 'text', 'navigation', 7008),
  ('openNow', 'Open now', 'مفتوح الآن', 'text', 'navigation', 7015),
  ('chooseLanguage', 'Choose your language', 'اختر لغتك', 'text', 'language', 8041),
  ('languageEnglish', 'English', 'English', 'text', 'language', 8042),
  ('languageArabic', 'العربية', 'العربية', 'text', 'language', 8043),
  ('switchToArabic', 'التبديل إلى العربية', 'التبديل إلى العربية', 'text', 'language', 8044),
  ('switchToEnglish', 'Switch to English', 'Switch to English', 'text', 'language', 8045),
  ('exploreMenu', 'Explore the menu', 'تصفح القائمة', 'text', 'general', 9013),
  ('findUs', 'Find us', 'موقعنا', 'text', 'general', 9014),
  ('itemsCount', 'items', 'صنفاً', 'text', 'general', 9027),
  ('from', 'from', 'ابتداءً من', 'text', 'general', 9028),
  ('across', 'across', 'في', 'text', 'general', 9031),
  ('staffSignIn', 'Staff', 'الموظفون', 'text', 'general', 9040)
on conflict (key) do nothing;

commit;
