-- 212 Café — the configured site, exported from the live database
--
-- GENERATED by scripts/export-content.mjs on 2026-08-27.
-- Do not hand-edit: change it in /admin/content and export again.
--
-- This is what makes a fresh clone reproduce what the owner set up. The live site is
-- still authoritative; this is its checked-in mirror. Uploaded images were downloaded
-- into public/uploads/ and the paths below rewritten to match, so a clone does not
-- depend on the Storage bucket.
--
-- Upserts, not inserts: re-running this brings a database up to the exported state
-- rather than failing on rows that already exist.

begin;

-- ------------------------------------------------------------------ theme
update site_theme set
  brand_ink          = '#14110f',
  brand_bone         = '#f6f1e7',
  brand_brass        = '#b08d4f',
  display_font       = 'Cormorant Garamond',
  body_font          = 'Inter',
  hero_image_path    = '/hero/katara-sunset-wide.webp',
  hero_portrait_path = '/hero/katara-sunset-portrait.webp',
  hero_focal_x       = 50,
  hero_focal_y       = 50,
  hero_zoom          = 1,
  corner_radius      = 'sm'
where id = 1;

-- ------------------------------------------------------------------- copy
insert into site_content (key, value_en, value_ar, kind, group_name, sort_order) values
  ('heroLocation', 'Marina Twin Tower A · 30th Floor · Lusail', 'برج مارينا التوأم أ · الطابق الثلاثون · لوسيل', 'text', 'hero', 1009),
  ('heroLine1', 'Coffee', 'قهوة', 'text', 'hero', 1010),
  ('heroLine2', 'above the city', 'فوق المدينة', 'text', 'hero', 1011),
  ('heroSub', 'Specialty coffee, desserts and brunch, thirty floors over Lusail Marina.', 'قهوة مختصة وحلويات وفطور متأخر، على ارتفاع ثلاثين طابقاً فوق مارينا لوسيل.', 'text', 'hero', 1012),
  ('viewEyebrow', 'The View', 'الإطلالة', 'text', 'view', 2017),
  ('viewTitle', 'Lusail’s best view, and we mean it.', 'أجمل إطلالة في لوسيل، ونعني ذلك.', 'text', 'view', 2018),
  ('viewBody1', 'From the 30th floor of Marina Twin Tower A, the Katara Towers curve out of the marina and the Gulf runs to the horizon. Every table is a window seat.', 'من الطابق الثلاثين في برج مارينا التوأم أ، تنحني أبراج كتارا خارجة من المارينا ويمتد الخليج حتى الأفق. كل طاولة هنا بإطلالة.', 'text', 'view', 2019),
  ('viewBody2', 'It is the reason people come once, and the reason they come back.', 'هو السبب في أن يزورنا الناس أول مرة، والسبب في عودتهم.', 'text', 'view', 2020),
  ('viewFullMenu', 'View full menu', 'عرض القائمة كاملة', 'text', 'view', 2026),
  ('signaturesEyebrow', 'Signatures', 'الأطباق المميزة', 'text', 'signatures', 3021),
  ('signaturesTitle', 'What we are known for', 'ما نشتهر به', 'text', 'signatures', 3022),
  ('signatureTag', 'Signature', 'مميز', 'text', 'signatures', 3023),
  ('menuEyebrow', 'The Menu', 'القائمة', 'text', 'menu', 4024),
  ('menuTitle', 'things worth the lift', 'صنفاً تستحق الصعود', 'text', 'menu', 4025),
  ('menuPageTitle', 'Everything we serve', 'كل ما نقدمه', 'text', 'menu', 4029),
  ('menuPageSub', 'sections. Prices in Qatari riyal.', 'أقسام. الأسعار بالريال القطري.', 'text', 'menu', 4030),
  ('closedNow', 'Closed', 'مغلق', 'text', 'visit', 5016),
  ('visitEyebrow', 'Visit', 'زورونا', 'text', 'visit', 5032),
  ('visitTitle', 'Thirty floors up', 'ثلاثون طابقاً للأعلى', 'text', 'visit', 5033),
  ('getDirections', 'Get directions', 'الاتجاهات', 'text', 'visit', 5034),
  ('hours', 'Hours', 'ساعات العمل', 'text', 'visit', 5035),
  ('closed', 'Closed', 'مغلق', 'text', 'visit', 5036),
  ('hoursNote', 'Hours are managed by the café and update here automatically.', 'يدير المقهى ساعات العمل وتُحدَّث هنا تلقائياً.', 'text', 'visit', 5037),
  ('footerBlurb', 'Specialty coffee, desserts and brunch, 30 floors above Lusail Marina.', 'قهوة مختصة وحلويات وفطور متأخر، ثلاثون طابقاً فوق مارينا لوسيل.', 'text', 'footer', 6038),
  ('footerAddress', 'Marina Twin Tower A, 30th Floor, Lusail, Qatar', 'برج مارينا التوأم أ، الطابق الثلاثون، لوسيل، قطر', 'text', 'footer', 6039),
  ('brandTagline', 'Lusail’s Best View', 'أجمل إطلالة في لوسيل', 'text', 'navigation', 7000),
  ('navView', 'The View', 'الإطلالة', 'text', 'navigation', 7001),
  ('navSignatures', 'Signatures', 'الأطباق المميزة', 'text', 'navigation', 7002),
  ('navMenu', 'Menu', 'القائمة', 'text', 'navigation', 7003),
  ('navVisit', 'Visit', 'زورونا', 'text', 'navigation', 7004),
  ('fullMenu', 'Full Menu', 'القائمة الكاملة', 'text', 'navigation', 7005),
  ('openMenu', 'Open menu', 'فتح القائمة', 'text', 'navigation', 7006),
  ('closeMenu', 'Close menu', 'إغلاق القائمة', 'text', 'navigation', 7007),
  ('back', 'Back', 'رجوع', 'text', 'navigation', 7008),
  ('openNow', 'Open now', 'مفتوح الآن', 'text', 'navigation', 7015),
  ('chooseLanguage', 'Choose your language', 'اختر لغتك', 'text', 'language', 8041),
  ('languageEnglish', 'English', 'English', 'text', 'language', 8042),
  ('languageArabic', 'العربية', 'العربية', 'text', 'language', 8043),
  ('switchToArabic', 'التبديل إلى العربية', 'التبديل إلى العربية', 'text', 'language', 8044),
  ('switchToEnglish', 'Switch to English', 'Switch to English', 'text', 'language', 8045),
  ('exploreMenu', 'Explore the menu', 'تصفح القائمة', 'text', 'general', 9013),
  ('findUs', 'Find us', 'موقعنا', 'text', 'general', 9014),
  ('itemsCount', 'items', 'صنفاً', 'text', 'general', 9027),
  ('from', 'from', 'ابتداءً من', 'text', 'general', 9028),
  ('across', 'across', 'في', 'text', 'general', 9031),
  ('staffSignIn', 'Staff', 'الموظفون', 'text', 'general', 9040)
on conflict (key) do update set
  value_en   = excluded.value_en,
  value_ar   = excluded.value_ar,
  kind       = excluded.kind,
  group_name = excluded.group_name,
  sort_order = excluded.sort_order;

-- --------------------------------------------------------------- business
update business_settings set
  name_en          = '212 Café',
  name_ar          = '٢١٢ كافيه',
  tagline_en       = 'Lusail''s Best View',
  tagline_ar       = 'أجمل إطلالة في لوسيل',
  address_en       = 'Marina Twin Tower A, 30th Floor, Lusail, Qatar',
  address_ar       = 'برج مارينا التوأم أ، الطابق الثلاثون، لوسيل، قطر',
  phone            = '+974 7011 2377',
  email            = '212.Qatar.24@gmail.com',
  instagram        = '212cafe.qatar',
  currency         = 'QAR',
  accepting_orders = true
where id = 1;

insert into business_hours (day_of_week, opens_at, closes_at, is_closed) values
  (0, '12:00:00', '00:00:00', false),
  (1, '12:00:00', '00:00:00', false),
  (2, '12:00:00', '00:00:00', false),
  (3, '12:00:00', '00:00:00', false),
  (4, '12:00:00', '00:00:00', false),
  (5, '12:00:00', '00:00:00', false),
  (6, '12:00:00', '00:00:00', false)
on conflict (day_of_week) do update set
  opens_at  = excluded.opens_at,
  closes_at = excluded.closes_at,
  is_closed = excluded.is_closed;

-- ------------------------------------------------- menu presentation
-- Category imagery.
update menu_categories set image_path = '/menu/0216-cortado.webp' where slug = 'hot-beverage';
update menu_categories set image_path = '/menu/0208-hiby-splash.webp' where slug = 'cold-beverage';
update menu_categories set image_path = '/menu/0049-brownies-chocolate-bomb.webp' where slug = 'sweets-pastry';
update menu_categories set image_path = '/menu/0155-halloumi-sandwich.webp' where slug = 'savoury';
update menu_categories set image_path = '/menu/0163-chicken-ceaser-salad.webp' where slug = 'salads';
update menu_categories set image_path = '/menu/0175-shakshooka.webp' where slug = 'brunch';

-- Signature selection, photography and approved copy, keyed on the café's own SKU.
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0002-americano.webp', description_en = 'Double shot of rich espresso diluted with hot water, creating a smooth, light-bodied cup with a full-flavored coffee aroma.', description_ar = 'شوت مزدوج من الإسبريسو الغني المخفف بالماء الساخن، ليمنحك كوباً متوازناً وخفيف القوام مع عبق القهوة الغني.' where sku = '0002';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0003-tiramisu-latte.webp', description_en = 'Espresso and steamed milk over a tiramisu syrup, finished with a dusting of cocoa.', description_ar = 'إسبريسو وحليب مبخّر مع شراب التيراميسو، ويُزيَّن برشّة من الكاكاو.' where sku = '0003';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0004-cappucino.webp', description_en = 'A rich shot of double espresso topped with equal parts steamed milk and a thick, silky layer of milk foam, dusted with cocoa powder.', description_ar = 'شوت غني من الإسبريسو المزدوج يعلوه مزيج متوازن من الحليب المبخر ورغوة الحليب المخملية الكثيفة، مع لمسة خفيفة من بودرة الكاكاو' where sku = '0004';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0005-chamomile-tea.webp', description_en = 'A soothing, caffeine-free infusion of premium whole chamomile flowers, offering a delicate floral aroma and subtle notes of honey.', description_ar = 'مزمور مهدئ وخالٍ من الكافيين من أزهار البابونج الكاملة الفاخرة، يتميز بنكهة زهرية لطيفة ولمسات خفيفة من العسل.' where sku = '0005';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0011-green-tea.webp', description_en = 'Loose-leaf green tea, steeped gently so it stays clean and grassy rather than bitter.', description_ar = 'شاي أخضر بأوراق كاملة، يُنقع برفق ليبقى نقياً ومنعشاً بلا مرارة.' where sku = '0011';
update menu_items set is_signature = true, copy_source = 'cafe', image_path = '/menu/0016-212-signature.webp', description_en = 'A rich shot of espresso blended with fresh milk, crushed Oreo, and our signature homemade chocolate sauce.', description_ar = 'جرعة غنية من الإسبريسو ممتزجة بالحليب الطازج، وقطع الأوريو المقرمشة، مع صوص الشوكولاتة الخاص المحضّر منزلياً' where sku = '0016';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0017-spanish-latte.webp', description_en = 'Espresso with condensed and steamed milk — sweeter and rounder than a standard latte.', description_ar = 'إسبريسو مع الحليب المكثّف والمبخّر — أحلى وأكثر نعومة من اللاتيه المعتاد.' where sku = '0017';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0018-latte.webp', description_en = 'Smooth, rich espresso combined with silky, steamed micro-foam milk for a perfectly balanced and velvety coffee experience.', description_ar = 'إسباديسو غني وناعم ممزوج بالحليب المبخر ذو الرغوة المخملية الحريرية، لتجربة قهوة متوازنة وفاخرة.' where sku = '0018';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0019-v60.webp', description_en = 'Coffee brewed by hand through a V60 cone, poured slowly for a clean, aromatic cup. Served black.', description_ar = 'قهوة تُحضَّر يدوياً عبر مصفاة V60، تُسكب ببطء لكوب نقي وعطر. تُقدَّم سادة.' where sku = '0019';
update menu_items set is_signature = true, copy_source = 'draft', image_path = '/menu/0034-the-3-layers.webp', description_en = 'Three layers in one glass — an espresso base, cold milk, and whipped coffee foam — finished with chocolate shavings.', description_ar = 'ثلاث طبقات في كوب واحد — قاعدة إسبريسو، وحليب بارد، ورغوة قهوة مخفوقة — مع رقائق الشوكولاتة.' where sku = '0034';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0039-normal-water.webp', description_en = 'Still bottled water, chilled.', description_ar = 'مياه معدنية غير غازية، مبرّدة.' where sku = '0039';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0040-sparkling-water.webp', description_en = 'Chilled sparkling water, served with ice and lemon on request.', description_ar = 'مياه غازية مبرّدة، تُقدَّم مع الثلج والليمون عند الطلب.' where sku = '0040';
update menu_items set is_signature = true, copy_source = 'cafe', image_path = '/menu/0049-brownies-chocolate-bomb.webp', description_en = 'Fresh homemade brownie topped with a bowl of creamy vanilla ice cream and warm specialty chocolate sauce to pour over and melt the top.', description_ar = 'براوني طازج ومحضر لدينا يعلوه وعاء من آيس كريم الفانيليا الكريمي مع صوص الشوكولاتة الخاص الدافئ للسكب فوقه وتذويب' where sku = '0049';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0052-the-french-toast.webp', description_en = 'Two pieces of golden, thick-cut artisan brioche soaked in a rich vanilla-cinnamon custard, seared to perfection. Served with salted caramel drizzle, fresh berries, and a side of vanilla ice cream.', description_ar = 'شريحتان سميكتان من خبز البريوش الذهبي الفاخر، مغمورتان في مزيج الكاسترد بالفانيليا والقرفة الغني ومحمصلتان بإتقان. تُقدّم مع لمسة من الكراميل المملح، الفواكه التوتية الطازجة، وجانب من أيس كريم الفانيليا.' where sku = '0052';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0056-turkey-sandwich.webp', description_en = 'Sliced turkey with rocket and tomato in a soft-baked roll, pressed until warm.', description_ar = 'شرائح ديك رومي مع الجرجير والطماطم في خبز طري، تُضغط حتى تدفأ.' where sku = '0056';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0058-cheese-croissant.webp', description_en = 'An all-butter croissant baked with cheese through the layers.', description_ar = 'كرواسون بالزبدة يُخبز مع الجبن بين طبقاته.' where sku = '0058';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0059-chocolate-croissant.webp', description_en = 'An all-butter croissant with dark chocolate folded into the layers.', description_ar = 'كرواسون بالزبدة مع الشوكولاتة الداكنة بين طبقاته.' where sku = '0059';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0066-eggs-benedict.webp', description_en = 'Crisp layered potato pavé topped with creamy mashed avocado, two perfectly poached eggs, and rich hollandaise sauce, finished with a pinch of sweet paprika, fresh rocca, and crumbled feta.', description_ar = 'طبقات البطاطس المقرمشة يعلوها مهروس الأفوكادو الكريمي، بيضتان مسلوقتان بدقة، وصوص الهولنديز الغني، مع لمسة من البابريكا الحلوة، الجرجير الطازج، ورشة من جبن الفيتا.' where sku = '0066';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0067-3-mini-sandwiches.webp', description_en = 'Crisp, donut-shaped artisanal falafel crafted from spiced chickpeas and fresh herbs, served over smooth tahini drizzle, garnished with pickled turnips, wild rocket, toasted sesame, and pomegranate seeds.', description_ar = 'فلافل حرفية مقرمشة على شكل دونات محضرة من الحمص المتبل والأعشاب الطازجة، تُقدّم فوق صوص الطحينة الناعمة، وتُزيَّن باللفت المخلل، الجرجير البري، السمسم المحمص، وحبات الرمان.' where sku = '0067';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0070-healthy-granola.webp', description_en = 'House-baked toasted oat granola blended with mixed nuts and seeds, served over silky Greek yogurt, topped with fresh seasonal berries, chia seeds, and a drizzle of pure honey.', description_ar = 'جرانولا الشوفان المخبوزة منزلیاً والمحمصة مع مكسرات وبذور مشكلة، تُقدّم فوق زبادي يوناني حريري، وتُزيَّن بالتوت الفاكهي الطازج، بذور الشيا، ورذاذ من العسل الصافي.' where sku = '0070';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0075-green-shakshooka.webp', description_en = 'Eggs baked into a green sauce of spinach and herbs, served in the dish they came out of the oven in.', description_ar = 'بيض مخبوز في صلصة خضراء من السبانخ والأعشاب، يُقدَّم في الإناء نفسه الخارج من الفرن.' where sku = '0075';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0076-penne-pasta.webp', description_en = 'Al dente penne folded into an Italian special sauce—a rich combination of three distinct sauces creating a creamy white base with tender pieces of chicken breast. Topped with aged Parmesan, white cheddar, and a pinch of fresh chives and parsley. Served with two slices of toasted bread to enjoy every drop of sauce.', description_ar = 'باستا البيني المطبوخة ببراعة وممزوجة بصلصة إيطالية خاصة,مزيج غني من ثلاثة أنواع مختلفة من الصلصات لابتكار قاعدة بيضاء كريمية مع قطع طرية من صدر الدجاج. تعلوها جُبنة البارميزان المعتقة، الشيدر الأبيض، ورشة البقدونس الطازج. تُقدّم مع شريحتين من الخبز المحمص للاستمتاع بآخر قطرة من الصلصة.' where sku = '0076';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0095-ceremonial-matcha-latte.webp', description_en = 'Japanese ceremonial matcha whisked to perfection and combined with smooth, velvety milk for a vibrant, earthy taste with natural sweetness. Served with a shot of espresso.', description_ar = 'ماتشا يابانية سيريمونيال مخفوقة بإتقان وممزوجة بالحليب المخملي الناعم، لمذاق غني ومنعش وحلاوة طبيعية. يُقدّم مع شوت إسبريسو.' where sku = '0095';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0101-affogato.webp', description_en = 'A scoop of rich, creamy vanilla gelato "drowned" in a freshly pulled shot of hot, double espresso. The perfect balance of hot and cold, sweet and bold.', description_ar = 'كرة من جيلاتو الفانيليا الغنية يسكب عليها "شوت" دافئ من الإسبريسو المزدوج الطازج. التوازن المثالي بين الحرارة والبرودة، والحلاوة والمرارة.' where sku = '0101';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0107-double-espresso.webp', description_en = 'A bold, concentrated double shot of specialty coffee, extracted to highlight rich flavors, natural sweetness, and a velvety crema layer.', description_ar = 'جرعة مضاعفة غنية ومكثفة من القهوة المختصة، تم استخلاصها بعناية لإبراز النكهات الغنية، الحلاوة الطبيعية، وطبقة الكريما المخملية.' where sku = '0107';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0108-english-breakfast-tea.webp', description_en = 'A classic, full-bodied black tea brew delivering a rich, robust malt flavor with a bright golden-amber hue and a refreshing finish.', description_ar = 'الشاي الأحمر الكلاسيكي الفاخر بعبير قوي ونكهة غنية ومكثفة، يتميز بلونه الذهبي الدافئ ولمسته المنعشة.' where sku = '0108';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0109-single-espresso.webp', description_en = 'A single shot, pulled short for a dense, syrupy cup.', description_ar = 'شوت واحد، يُستخلص قصيراً لكوب كثيف وغني.' where sku = '0109';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0110-flat-white.webp', description_en = 'A double shot of rich espresso topped with velvety, micro-foamed steamed milk for a smooth, coffee-forward taste and silky mouthfeel.', description_ar = 'جرعة مضاعفة من الإسبريسو الغني تعلوها رغوة حليب ناعمة ومخملية لمذاق متوازن يبرز نكهة القهوة الغنية وقوام حريري.' where sku = '0110';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0115-non-coffee-matcha.webp', description_en = 'Japanese matcha whisked to perfection and paired with silky, steamed micro-foam milk for a smooth, earthy, and antioxidant-rich beverage.', description_ar = 'ما تشا يابانية فاخرة بدرجة احتفالية مقتناة بعناية، مخفوقة بإتقان وممزوجة مع الحليب المبخر ذو الرغوة المخملية لمشروب ناعم، غني ومضاد للأكسدة.' where sku = '0115';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0120-unique-strawberry-matcha.webp', description_en = 'Crushed strawberries under cold milk and a bright layer of matcha, finished with mint.', description_ar = 'فراولة مهروسة تحت حليب بارد وطبقة زاهية من الماتشا، وتُزيَّن بالنعناع.' where sku = '0120';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0132-fresh-orange-juice.webp', description_en = '100% freshly squeezed ripe oranges, naturally sweet, vibrant, and packed with refreshing citrus taste.', description_ar = 'عصير برتقال طازج 100٪ من حبات البرتقال الناضجة، بحلاوة طبيعية ونكهة حمضية منعشة.' where sku = '0132';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0135-limited-colada.webp', description_en = 'A signature seasonal beverage layered with sweet pineapple juice and rich, thick mango juice, topped with silky coconut cream and finished with a crispy coconut crunch.', description_ar = 'مشروب موسمي مميز بطبقات من عصير الأناناس الحلو وعصير المانجو الكثيف، تعلوه كريمة جوز الهند الحريرية ومُزيّن بقرمشة جوز الهند الطازجة.' where sku = '0135';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0143-ice-tissu-cake.webp', description_en = 'An exquisite creation crafted in the shape of roasted coffee beans, featuring ultra-thin, tissue-soft layered cake infused with chilled cream and rich cocoa.', description_ar = 'ابتكار فني ساحر على شكل حبوب القهوة المحمصة، يتميز بطبقات كيك ناعمة ورقيقة كالأنسجة، محشوة بالكريمة الباردة والكاكاو الغني.' where sku = '0143';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0155-halloumi-sandwich.webp', description_en = 'Pan-seared golden halloumi layered in warm artisan brioche with signature za''atar, fresh homemade green pesto, smooth avocado guacamole, wild rocket, and sliced tomato, finished with extra virgin olive oil and sweet pomegranate molasses.', description_ar = 'شرائح جبن الحلوم الذهبية المحمرة في خبز البريوش الحرفي الدافئ مع الزعتر الفاخر، بيستو الأعشاب الخضراء المحضر منزلياً، واكامولي الأفوكادو الناعم، جرجير بري، وشرائح الطماطم، تعلوها لمسة من زيت الزيتون البكر ودبس الرمان الحلو.' where sku = '0155';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0157-cheesy-roasted-beef-sandwich.webp', description_en = 'Tender roasted beef strips layered with rich homemade red pesto, melted mozzarella cheese, fresh tomato slices, and crisp greens, served warm in a toasted artisan bun.', description_ar = 'شرائح لحم بقر مشوي طرية مع صوص البيستو الأحمر المحضّر لدينا، جبن الموزاريلا المذاب، شرائح الطماطم الطازجة، والخضار الخضراء المنعشة، تُقدّم دافئة في خبز محمص فاخر.' where sku = '0157';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0160-plain-croissant.webp', description_en = 'An all-butter croissant, baked for a crisp shell and an open, layered crumb.', description_ar = 'كرواسون بالزبدة، يُخبز ليكون مقرمشاً من الخارج وهشاً بطبقاته.' where sku = '0160';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0163-chicken-ceaser-salad.webp', description_en = 'Tender grilled chicken breast served over crisp romaine lettuce, tossed in rich Caesar dressing, topped with shaved Parmesan cheese and garlic butter croutons.', description_ar = 'شرائح صدور الدجاج المشوية الطرية على طبقة من خس الرومين الطازج، ممزوجة بصلصة السيزر الغنية، يعلوها جبن البارميزان المبشور ومكعبات الخبز المحمص بالثوم والزبدة.' where sku = '0163';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0175-shakshooka.webp', description_en = 'Two eggs gently cooked and nestled in a rich, slow-simmered sauce of vine-ripened tomatoes, a sweet bell pepper mixture, garlic, and aromatic Mediterranean spices. Served warm with artisan Arabic bread.', description_ar = 'بيضتان مطهوتان ببراعة ورفق داخل صلصة غنية ومطهوة ببطء من الطماطم الناضجة، مزيج الفلفل الرومي الحلو، الثوم، والتوابل المتوسطية العطرية. تُقدّم دافئة مع الخبز العربي المخبوز على الطريقة الحرفية.' where sku = '0175';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0201-rocca-with-quinoa.webp', description_en = 'Crisp rocket leaves and fluffy organic quinoa tossed with cherry tomatoes, fresh pomegranate seeds, toasted nuts, and crunchy baked corn pieces, served with tender grilled chicken breast . Finished with a signature blend of balsamic vinaigrette and zesty Italian dressing.', description_ar = 'أوراق الجرجير الطازجة مع الكينوا العضوية الهشة، مطعّمة بطماطم شيري، حبات الرمان الطازجة، المكسرات المحمصة، وقطع الذرة ، تُقدّم مع صدر الدجاج المشوي الطري. ممزوجة بلمسة خاصة من صلصة البلسميك والتتبيلة الإيطالية المنعشة.' where sku = '0201';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0202-barbecue-chicken-sandwich.webp', description_en = 'Tender, shredded grilled chicken tossed in a rich, smoky barbecue sauce, topped with melted cheese, fresh pomegranate seeds, and toasted pumpkin seeds, served inside a toasted brioche bun.', description_ar = 'شرائح دجاج مشوية وطرية ممزوجة بصوص الباربكيو المدخن والغني، يعلوها الجبن المذاب، حبات الرمان الطازجة، وبذور القرع المحمصة، تقدم داخل خبز البريوش المحمص.' where sku = '0202';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0203-cheese-cake.webp', description_en = 'Set cheesecake, plated with a cocoa crumb and fresh berries.', description_ar = 'تشيز كيك يُقدَّم مع فتات الكاكاو والتوت الطازج.' where sku = '0203';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0204-pecan-melt.webp', description_en = 'An exquisite dessert sculpted in the shape of a pecan nut, filled with signature homemade cream, a dual-biscuit base, and rich melted caramel, topped with a crunchy pecan nut finish.', description_ar = 'حلوى مبتكرة ومصممة على شكل حبة البيكان، محشوة بالكريمة الخاصة المنزلية، طبقتين من البسكويت الهش، والكراميل الذائب، تعلوها مقرمشات البيكان المحمصة.' where sku = '0204';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0205-golden-hive-cake.webp', description_en = 'Delicate, golden layers of honey-infused cake separated by light, velvety cream, finished with a subtle honey-crumb topping.', description_ar = 'طبقات ذهبية رقيقة وهشة من الكيك المحضر بعسل النحل الطبيعي، تفصل بينها كريمة مخملية خفيفة، ومتوجة بفتات العسل الهش.' where sku = '0205';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0206-double-d.webp', description_en = 'Rich chocolate sponge layered with creamy espresso-infused filling, nestled between two distinct house-made biscuits, topped with melted rich chocolate and a crunchy chocolate crumble.', description_ar = 'كيكة إسفنجية بالشوكلاتة الغنية مع طبقات من الكريمة بنكهة الإسبريسو، بين نوعين من البسكويت المحضر لدينا، يغلوها الشوكولاتة الغنية المذابة مع كرانشي الشوكولاتة المقرمش.' where sku = '0206';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0207-tuna-avocado.webp', description_en = 'Tuna and crushed avocado with tomato on toasted seeded bread.', description_ar = 'تونة مع الأفوكادو المهروس والطماطم على خبز محمّص بالبذور.' where sku = '0207';
update menu_items set is_signature = true, copy_source = 'cafe', image_path = '/menu/0208-hiby-splash.webp', description_en = 'A vibrant cold-pressed iced hibiscus tea infused with peach and mixed berry flavor, bright citrus, and fresh mint.', description_ar = 'شاي كركديه بارد ومعصور على البارد غني بنكهات الخوخ والتوت المشكل، الحمضيات المنعشة، والنعناع الطازج.' where sku = '0208';
update menu_items set is_signature = true, copy_source = 'draft', image_path = '/menu/0209-mango-red-horizon.webp', description_en = 'Mango and red berry poured in layers over ice so the colours stay apart — made to be looked at against the marina.', description_ar = 'مانجو وتوت أحمر يُسكبان بطبقات فوق الثلج لتبقى الألوان منفصلة — صُنع ليُنظر إليه أمام المارينا.' where sku = '0209';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0210-passion-wave.webp', description_en = 'Passion fruit over berry with a wheel of lemon and mint — tart, cold and bright.', description_ar = 'باشون فروت فوق التوت مع شريحة ليمون ونعناع — منعش وبارد وزاهٍ.' where sku = '0210';
update menu_items set is_signature = false, copy_source = 'draft', image_path = '/menu/0211-sunrise.webp', description_en = 'Citrus and grenadine poured to fade from orange to red, like the hour it is named after.', description_ar = 'حمضيات وشراب الرمان يتدرّجان من البرتقالي إلى الأحمر، كالساعة التي حمل اسمها.' where sku = '0211';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0212-greek-omlette.webp', description_en = 'Fluffy eggs folded with tangy Greek feta cheese, sweet cherry tomatoes, Kalamata olives, and fresh greens, finished with aromatic oregano and delicate herbs.', description_ar = 'بيض هشش مطوي مع جبن الفيتا اليوناني الفاخر، الطماطم الكرزية الحلوة، زيتون الكالاماتا، والأوراق الخضراء الطازجة، يُكَمَّل بنكهة الزعتر البري والأعشاب العطرية.' where sku = '0212';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0213-french-omlette.webp', description_en = 'Smooth, golden, and soft-folded eggs with a rich, velvety center, finished with a brush of fine butter and freshly chopped herbs.', description_ar = 'بيض مطوي بعناية بقوام ذهبي أملس ومركز كريمي طري، مطلي بلمسة من الزبدة الفاخرة ومزين بالأعشاب الطازجة.' where sku = '0213';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0214-creamy-egg-with-chicken.webp', description_en = 'Velvety soft-scrambled eggs paired with tender herb-marinated chicken, served over toasted artisan brioche and garnished with fresh chives.', description_ar = 'بيض مخفوق ناعم ومخملي يُقدّم مع دجاج طري متبل بالأعشاب، فوق شريحة من خبز البريوش المحمص ومزين بالثوم المعمر الطازج.' where sku = '0214';
update menu_items set is_signature = false, copy_source = 'cafe', image_path = '/menu/0216-cortado.webp', description_en = 'A precise 1:1 balance of rich espresso cut with equal parts warm, silky steamed milk, served in a classic glass.', description_ar = 'توازن دقيق بنسبة 1:1 من الإسبريسو الغني مع كمية مساوية من الحليب المبخر الدافئ والمخملي، يُقدّم في كوب زجاجي كلاسيكي.' where sku = '0216';

commit;
